# GitHub Pages config
title: Kasula Vasanth — Portfolio
description: IBM-certified Data Scientist & AI/ML Engineer
url: "https://vasanthkasula.github.io"
baseurl: "/vasanth-portfolio"
theme: null
plugins: []
